version: '2'
services:
    eauction-app:
        image: eauction
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://eauction-mysql:3306/eauction?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    eauction-mysql:
        extends:
            file: mysql.yml
            service: eauction-mysql
