export * from './item-attribute.model';
export * from './item-attribute-popup.service';
export * from './item-attribute.service';
export * from './item-attribute-dialog.component';
export * from './item-attribute-delete-dialog.component';
export * from './item-attribute-detail.component';
export * from './item-attribute.component';
export * from './item-attribute-list/item-attribute-list.component';
export * from './item-attribute.route';
